# Generated by Django 5.0.6 on 2024-07-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbt', '0002_alter_toolboxtalk_last_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxtalk',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
