# Generated by Django 5.0.6 on 2024-07-19 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbt', '0003_alter_toolboxtalk_last_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolboxtalk',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='toolboxtalk',
            name='last_updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_tbts', to=settings.AUTH_USER_MODEL),
        ),
    ]
