# Generated by Django 5.0.6 on 2024-09-04 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0022_alter_worksiterole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SafetyObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('work_location', models.CharField(max_length=155)),
                ('department', models.CharField(choices=[('electrical', 'Electrical'), ('civil', 'Civil'), ('mechanical', 'Mechanical'), ('stores', 'Stores')], max_length=155)),
                ('activity_performed', models.TextField()),
                ('type_of_observation', models.CharField(choices=[('unsafe_act', 'Unsafe Act'), ('unsafe_condition', 'Unsafe Condition')], max_length=155)),
                ('classification', models.CharField(max_length=155)),
                ('risk_rated', models.CharField(choices=[('high', 'High'), ('significant', 'Significant'), ('medium', 'Medium'), ('low', 'Low')], max_length=155)),
                ('action_taken_or_required', models.TextField()),
                ('reported_by', models.CharField(max_length=155)),
                ('observation_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=155)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='safety_observation')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='safety_observation')),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('corrective_action_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_observations_corrective_action_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_safety_observations', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_safety_observations', to=settings.AUTH_USER_MODEL)),
                ('sub_contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_observations_sub_contractor', to=settings.AUTH_USER_MODEL)),
                ('work_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.worksite')),
            ],
        ),
    ]
