# Generated by Django 5.0.6 on 2024-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='safety_observation_found',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
