# Generated by Django 5.0.6 on 2024-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0003_rename_closing_date_safetyobservation_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
