# Generated by Django 5.0.6 on 2024-09-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0004_safetyobservation_closed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyobservation',
            name='action_taken_or_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetyobservation',
            name='before_image',
            field=models.ImageField(default='hi', upload_to='safety_observation'),
            preserve_default=False,
        ),
    ]
