# Generated by Django 5.0.6 on 2024-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0005_alter_safetyobservation_action_taken_or_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationclassification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
