# Generated by Django 5.0.6 on 2024-09-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0006_alter_observationclassification_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationclassification',
            name='description',
        ),
    ]
