# Generated by Django 5.0.6 on 2024-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0007_remove_observationclassification_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyobservation',
            name='action_taken_or_required',
        ),
        migrations.AddField(
            model_name='safetyobservation',
            name='corrective_action_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyobservation',
            name='corrective_action_taken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
