# Generated by Django 5.0.6 on 2024-09-08 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0009_alter_safetyobservation_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyobservation',
            name='created_under',
        ),
        migrations.AlterField(
            model_name='safetyobservation',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_observations_reported_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
