# Generated by Django 5.0.6 on 2024-09-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0012_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveactionuser',
            name='department',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('civil', 'Civil'), ('mechanical', 'Mechanical'), ('stores', 'Stores')], max_length=155),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
