# Generated by Django 5.0.6 on 2024-09-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_worksiterole_role'),
        ('safety_observation', '0014_remove_correctiveactionuser_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correctiveactionuser',
            unique_together={('work_site', 'department')},
        ),
    ]
