# Generated by Django 5.0.6 on 2024-09-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0015_alter_correctiveactionuser_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrectiveActionUser',
        ),
    ]
