# Generated by Django 5.0.6 on 2024-09-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0016_delete_correctiveactionuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyobservation',
            name='due_date',
        ),
    ]
