# Generated by Django 5.0.6 on 2024-09-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0017_remove_safetyobservation_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyobservation',
            name='department',
        ),
    ]
