# Generated by Django 5.0.6 on 2024-09-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_department_alter_correctiveactionuser_work_site_and_more'),
        ('safety_observation', '0018_remove_safetyobservation_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.department'),
            preserve_default=False,
        ),
    ]
