# Generated by Django 5.0.6 on 2024-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_observation', '0019_safetyobservation_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyobservation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('verification_required', 'Verification Required')], default='open', max_length=25),
            preserve_default=False,
        ),
    ]
