# Generated by Django 5.0.6 on 2024-10-13 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0029_alter_correctiveactionuser_work_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permit_no', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateField()),
                ('validity', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('epc_approved', 'EPC Approved'), ('epc_rejected', 'EPC Rejected'), ('client_approved', 'Client Approved'), ('client_rejected', 'Client Rejected'), ('closed', 'Closed')], default='submitted', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(max_length=155)),
                ('lock_out_no', models.CharField(max_length=155)),
                ('location', models.CharField(max_length=155)),
                ('work_order_no', models.CharField(max_length=155)),
                ('job_description', models.TextField()),
                ('issued_to', models.CharField(max_length=155)),
                ('tool_box_talk', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A')], max_length=255)),
                ('underground_or_overhead_cables_checked', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=255, verbose_name='Underground or overhead cables checked for intervention')),
                ('ppe_required_to_be_used', models.JSONField()),
                ('other_work_permit_issued_same_location_datetime', models.BooleanField()),
                ('other_permit_no', models.CharField(blank=True, max_length=155, null=True)),
                ('any_other_safety_precaution_required', models.TextField(blank=True, null=True, verbose_name='Any other safety precaution required?')),
                ('site_safety_induction', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_ptws', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_%(class)s_ptws', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_ptws', to=settings.AUTH_USER_MODEL)),
                ('work_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
