# Generated by Django 5.0.6 on 2024-10-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0002_alter_general_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='expires_at',
            field=models.DateTimeField(default='2024-10-13 14:30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='general',
            name='site_safety_induction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='validity',
            field=models.CharField(max_length=155),
        ),
    ]
