# Generated by Django 5.0.6 on 2024-10-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0003_general_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='underground_or_overhead_cables_checked',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('n/a', 'N/A')], max_length=255, verbose_name='Underground or overhead cables checked for intervention'),
        ),
    ]
