# Generated by Django 5.0.6 on 2024-10-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0004_alter_general_underground_or_overhead_cables_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='general',
            name='validity',
            field=models.DateTimeField(),
        ),
    ]
