# Generated by Django 5.0.6 on 2024-10-18 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0005_remove_general_expires_at_alter_general_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
