# Generated by Django 5.0.6 on 2024-10-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0006_general_submitted_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_ptws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='general',
            name='accepted_by_signature',
            field=models.ImageField(blank=True, null=True, upload_to='ptw/signatures/'),
        ),
        migrations.AddField(
            model_name='general',
            name='accepted_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_ptws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='general',
            name='approved_by_signature',
            field=models.ImageField(blank=True, null=True, upload_to='ptw/signatures/'),
        ),
        migrations.AddField(
            model_name='general',
            name='approved_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='submitted_by_signature',
            field=models.ImageField(blank=True, null=True, upload_to='ptw/signatures/'),
        ),
    ]
