# Generated by Django 5.0.6 on 2024-10-20 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0007_general_accepted_by_general_accepted_by_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='approved_by_signature',
            new_name='verified_by_signature',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='approved_datetime',
            new_name='verified_datetime',
        ),
        migrations.RemoveField(
            model_name='general',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='general',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_ptws', to=settings.AUTH_USER_MODEL),
        ),
    ]
