# Generated by Django 5.0.6 on 2024-10-21 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0009_alter_general_submitted_by_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_ptws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='general',
            name='rejected_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
