# Generated by Django 5.0.6 on 2024-10-23 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0014_general_extend_till_general_extension_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='extend_till',
        ),
        migrations.RemoveField(
            model_name='general',
            name='extension_status',
        ),
        migrations.AddField(
            model_name='general',
            name='closure_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closure_accepted_ptws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='general',
            name='closure_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='general',
            name='closure_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closure_request_ptws', to=settings.AUTH_USER_MODEL),
        ),
    ]
