# Generated by Django 5.0.6 on 2024-10-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0015_remove_general_extend_till_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='closure_request',
        ),
        migrations.AddField(
            model_name='general',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='closrue_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
