# Generated by Django 5.0.6 on 2024-10-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0016_remove_general_closure_request_general_closed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='closrue_requested_at',
            new_name='closure_requested_at',
        ),
    ]
