# Generated by Django 5.0.6 on 2024-07-19 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0009_alter_worksiterole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(editable=False)),
                ('number_of_workers', models.PositiveIntegerField()),
                ('verification_status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Revise', 'Revise')], default='Not Verified', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_manpowers', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_manpowers', to=settings.AUTH_USER_MODEL)),
                ('sub_contractor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='manpower_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_manpowers', to=settings.AUTH_USER_MODEL)),
                ('work_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.worksite')),
            ],
        ),
        migrations.AddConstraint(
            model_name='manpower',
            constraint=models.UniqueConstraint(fields=('work_site', 'date', 'sub_contractor'), name='unique_manpower_report'),
        ),
    ]
