# Generated by Django 5.0.6 on 2024-07-19 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpower',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manpower',
            name='sub_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manpower_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
