# Generated by Django 5.0.6 on 2024-08-12 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ExcavationInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField()),
                ('description', models.TextField()),
                ('date_of_checking', models.DateField()),
                ('ref_drawing_no', models.CharField()),
                ('checked_by_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('checked_by_date', models.DateField()),
                ('witnessed_by_1_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('witnessed_by_1_date', models.DateField(blank=True, null=True)),
                ('witnessed_by_2_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('witnessed_by_2_date', models.DateField(blank=True, null=True)),
                ('witnessed_by_3_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('witnessed_by_3_date', models.DateField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_inspections', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_1', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_2', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection.inspectioncategory')),
            ],
        ),
    ]
