# Generated by Django 5.0.6 on 2024-08-12 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_user_email'),
        ('inspection', '0002_inspection_delete_excavationinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_by_signature', models.ImageField(upload_to='signatures/')),
                ('checked_by_date', models.DateField()),
                ('witnessed_by_1_signature', models.ImageField(upload_to='signatures/')),
                ('witnessed_by_1_date', models.DateField()),
                ('witnessed_by_2_signature', models.ImageField(upload_to='signatures/')),
                ('witnessed_by_2_date', models.DateField()),
                ('witnessed_by_3_signature', models.ImageField(upload_to='signatures/')),
                ('witnessed_by_3_date', models.DateField()),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_inspections', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_1', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_2', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_3', to=settings.AUTH_USER_MODEL)),
                ('work_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.worksite')),
            ],
        ),
        migrations.CreateModel(
            name='ExacavationForm',
            fields=[
                ('abstractinspection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inspection.abstractinspection')),
                ('project_name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('date_of_checking', models.DateField()),
                ('ref_drawing_no', models.CharField(max_length=155)),
                ('fields', models.ManyToManyField(to='inspection.inspectionitem')),
            ],
            bases=('inspection.abstractinspection',),
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
