# Generated by Django 5.0.6 on 2024-08-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_excavation_created_at_excavation_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractinspection',
            name='checked_by_signature',
        ),
        migrations.RemoveField(
            model_name='abstractinspection',
            name='witnessed_by_1_signature',
        ),
        migrations.RemoveField(
            model_name='abstractinspection',
            name='witnessed_by_2_signature',
        ),
        migrations.RemoveField(
            model_name='abstractinspection',
            name='witnessed_by_3_signature',
        ),
    ]
