# Generated by Django 5.0.6 on 2024-08-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_remove_abstractinspection_checked_by_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractinspection',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='abstractinspection',
            name='witnessed_by_1',
        ),
        migrations.RemoveField(
            model_name='abstractinspection',
            name='witnessed_by_2',
        ),
        migrations.RemoveField(
            model_name='abstractinspection',
            name='witnessed_by_3',
        ),
        migrations.RemoveField(
            model_name='abstractinspection',
            name='work_site',
        ),
        migrations.RemoveField(
            model_name='excavation',
            name='abstractinspection_ptr',
        ),
        migrations.RemoveField(
            model_name='excavation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='excavation',
            name='last_updated_by',
        ),
        migrations.DeleteModel(
            name='InspectionCategory',
        ),
        migrations.DeleteModel(
            name='AbstractInspection',
        ),
        migrations.DeleteModel(
            name='Excavation',
        ),
    ]
