# Generated by Django 5.0.6 on 2024-08-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0021_alter_user_email'),
        ('inspection', '0009_remove_abstractinspection_checked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excavation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_by_date', models.DateField()),
                ('witnessed_by_1_date', models.DateField()),
                ('witnessed_by_2_date', models.DateField()),
                ('witnessed_by_3_date', models.DateField()),
                ('project_name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('date_of_checking', models.DateField()),
                ('ref_drawing_no', models.CharField(max_length=155)),
                ('other_specifications', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_inspections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_excavations', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_excavations', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_1', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_2', to=settings.AUTH_USER_MODEL)),
                ('witnessed_by_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_inspections_3', to=settings.AUTH_USER_MODEL)),
                ('work_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
