# Generated by Django 5.0.6 on 2024-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavation',
            name='other_specifications',
        ),
        migrations.AddField(
            model_name='excavation',
            name='fields',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
