# Generated by Django 5.0.6 on 2024-08-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_remove_excavation_other_specifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excavation',
            old_name='fields',
            new_name='checklists',
        ),
    ]
