# Generated by Django 5.0.6 on 2024-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0012_rename_fields_excavation_checklists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excavation',
            old_name='witnessed_by_1',
            new_name='witness_1',
        ),
        migrations.RenameField(
            model_name='excavation',
            old_name='witnessed_by_1_date',
            new_name='witness_1_date',
        ),
        migrations.RenameField(
            model_name='excavation',
            old_name='witnessed_by_2',
            new_name='witness_2',
        ),
        migrations.RenameField(
            model_name='excavation',
            old_name='witnessed_by_2_date',
            new_name='witness_2_date',
        ),
        migrations.RenameField(
            model_name='excavation',
            old_name='witnessed_by_3',
            new_name='witness_3',
        ),
        migrations.RenameField(
            model_name='excavation',
            old_name='witnessed_by_3_date',
            new_name='witness_3_date',
        ),
        migrations.AddField(
            model_name='excavation',
            name='witness_1_approval_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved')], default='initiated', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excavation',
            name='witness_2_approval_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved')], default='initiated', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excavation',
            name='witness_3_approval_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved')], default='initiated', max_length=15),
            preserve_default=False,
        ),
    ]
