# Generated by Django 5.0.6 on 2024-08-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0013_rename_witnessed_by_1_excavation_witness_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavation',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='inspection/excavation/'),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='checked_by_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_1_approval_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('approved', 'Approved')], max_length=15),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_2_approval_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('approved', 'Approved')], max_length=15),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_3_approval_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('approved', 'Approved')], max_length=15),
        ),
    ]
