# Generated by Django 5.0.6 on 2024-08-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0014_excavation_document_alter_excavation_checked_by_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavation',
            name='witness_1_approval_status',
        ),
        migrations.RemoveField(
            model_name='excavation',
            name='witness_2_approval_status',
        ),
        migrations.RemoveField(
            model_name='excavation',
            name='witness_3_approval_status',
        ),
        migrations.AddField(
            model_name='excavation',
            name='approval_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('approved', 'Approved')], default='initiated', max_length=15),
        ),
        migrations.AddField(
            model_name='excavation',
            name='witness_1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excavation',
            name='witness_2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excavation',
            name='witness_3_approved',
            field=models.BooleanField(default=False),
        ),
    ]
