# Generated by Django 5.0.6 on 2024-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0016_alter_excavation_checked_by_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavation',
            name='checked_by_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_3_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
