# Generated by Django 5.0.6 on 2024-08-24 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0018_excavation_witness_1_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excavation',
            name='id',
        ),
        migrations.AddField(
            model_name='excavation',
            name='kid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
