# Generated by Django 5.0.6 on 2024-08-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0019_remove_excavation_id_excavation_kid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excavation',
            old_name='kid',
            new_name='id',
        ),
    ]
