# Generated by Django 5.0.6 on 2024-08-28 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_worksiterole_role'),
        ('inspection', '0021_alter_excavation_checked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavation',
            name='checked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_witness_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_witness_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excavation',
            name='witness_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_witness_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AntiTermiteTreatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_by_date', models.DateField(auto_now_add=True)),
                ('witness_1_date', models.DateField(blank=True, null=True)),
                ('witness_1_signature', models.ImageField(blank=True, null=True, upload_to='inspection/signatures/')),
                ('witness_1_approved', models.BooleanField(default=False)),
                ('witness_2_date', models.DateField(blank=True, null=True)),
                ('witness_2_signature', models.ImageField(blank=True, null=True, upload_to='inspection/signatures/')),
                ('witness_2_approved', models.BooleanField(default=False)),
                ('witness_3_date', models.DateField(blank=True, null=True)),
                ('witness_3_signature', models.ImageField(blank=True, null=True, upload_to='inspection/signatures/')),
                ('witness_3_approved', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('approved', 'Approved')], default='initiated', max_length=15)),
                ('project_name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('date_of_checking', models.DateField()),
                ('ref_drawing_no', models.CharField(max_length=155)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_checked_by', to=settings.AUTH_USER_MODEL)),
                ('witness_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_witness_1', to=settings.AUTH_USER_MODEL)),
                ('witness_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_witness_2', to=settings.AUTH_USER_MODEL)),
                ('witness_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_witness_3', to=settings.AUTH_USER_MODEL)),
                ('work_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
