# Generated by Django 5.0.6 on 2024-09-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0027_htcable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htcable',
            old_name='project_name',
            new_name='site_location_or_area',
        ),
    ]
