# Generated by Django 5.0.6 on 2024-09-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0032_culvertwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culvertwork',
            old_name='serial_no',
            new_name='site_location_or_area',
        ),
    ]
