# Generated by Django 5.0.6 on 2024-09-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0034_dcdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DCDB',
        ),
    ]
