# Generated by Django 5.0.6 on 2024-09-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0035_delete_dcdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaincementconcretework',
            old_name='grade_or_mix',
            new_name='grade_or_mix_proportion_of_concrete',
        ),
        migrations.RemoveField(
            model_name='plaincementconcretework',
            name='proportion_of_concrete',
        ),
    ]
