# Generated by Django 5.0.6 on 2024-09-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0042_plastering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plastering',
            name='comments',
        ),
    ]
