# Generated by Django 5.0.6 on 2024-09-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0046_rename_comments_or_remarks_dcdb_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcdb',
            old_name='comments',
            new_name='comments_or_remarks',
        ),
    ]
