# Generated by Django 5.0.6 on 2024-09-26 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0049_potentialtransformer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialtransformer',
            name='witness_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_witness_3', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potentialtransformer',
            name='witness_3_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='potentialtransformer',
            name='witness_3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialtransformer',
            name='witness_3_signature',
            field=models.ImageField(blank=True, null=True, upload_to='inspection/signatures/'),
        ),
    ]
