# Generated by Django 5.0.6 on 2024-09-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0051_batterybankandbatterycharger_controlcablelaying_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inverter',
            old_name='comments',
            new_name='comments_or_remarks',
        ),
        migrations.RenameField(
            model_name='stringcables',
            old_name='comments',
            new_name='comments_or_remarks',
        ),
    ]
