# Generated by Django 5.0.6 on 2024-10-07 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_correctiveactionuser_work_site'),
        ('inspection', '0056_inverterroomorcontrolroombuilding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InverterRoomOrControlRoomBuilding',
            new_name='InverterOrControlRoomBuilding',
        ),
    ]
