# Generated by Django 5.0.6 on 2024-10-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0058_earthingsystem_htcableprecomm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthingsystem',
            old_name='data',
            new_name='earth_tester_details',
        ),
        migrations.RemoveField(
            model_name='earthingsystem',
            name='calibration_details',
        ),
        migrations.RemoveField(
            model_name='earthingsystem',
            name='make',
        ),
        migrations.RemoveField(
            model_name='earthingsystem',
            name='range',
        ),
        migrations.RemoveField(
            model_name='earthingsystem',
            name='serial_no',
        ),
    ]
