# Generated by Django 5.0.6 on 2024-07-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='registered_under',
            new_name='created_under',
        ),
    ]
