# Generated by Django 5.0.6 on 2024-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_worker_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
