# Generated by Django 5.0.6 on 2024-08-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_worker_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='image',
        ),
    ]
