# Generated by Django 5.0.6 on 2024-08-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_remove_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='worker',
            name='designation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='worker',
            name='father_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='worker',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
