# Generated by Django 5.0.6 on 2024-08-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_alter_worker_city_alter_worker_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='worker/profile_pictures/'),
        ),
    ]
