# Generated by Django 5.0.6 on 2024-08-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_worker_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
