# Generated by Django 5.0.6 on 2024-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_rename_profile_picture_worker_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='profile_pic',
            field=models.ImageField(default='https://res.cloudinary.com/dbbmdq3uy/image/upload/v1725044492/Assets/user_woot6s.png', upload_to='worker/profile_pictures/'),
        ),
    ]
