# Generated by Django 5.0.6 on 2024-07-15 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_worksite_worksiterole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksiterole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
