# Generated by Django 5.0.6 on 2024-07-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_worksiterole_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksiterole',
            old_name='worksite',
            new_name='work_site',
        ),
    ]
