# Generated by Django 5.0.6 on 2024-07-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_worksite_worksiterole_work_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksiterole',
            unique_together={('user', 'work_site')},
        ),
    ]
