# Generated by Django 5.0.6 on 2024-07-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_worksiterole_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worksiterole',
            name='role',
            field=models.CharField(choices=[('epc_admin', 'EPC Admin'), ('epc', 'EPC'), ('client', 'Client'), ('subcontractor', 'Subcontractor')], max_length=50),
        ),
    ]
