# Generated by Django 5.0.6 on 2024-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_worksiterole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksiterole',
            name='role',
            field=models.CharField(choices=[('epc', 'EPC'), ('client', 'Client'), ('sub_contractor', 'Subcontractor')], max_length=50),
        ),
    ]
