# Generated by Django 5.0.6 on 2024-07-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_worksiterole_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_epc_admin',
        ),
    ]
