# Generated by Django 5.0.6 on 2024-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_worksite_name_alter_worksite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='name',
            field=models.CharField(default='Test name', max_length=45),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
