# Generated by Django 5.0.6 on 2024-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_worksite_name_alter_worksite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
