# Generated by Django 5.0.6 on 2024-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_worksite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
