# Generated by Django 5.0.6 on 2024-07-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_worksite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksiterole',
            name='role',
            field=models.CharField(choices=[('epc_admin', 'EPC Admin'), ('epc', 'EPC User'), ('client', 'Client User'), ('sub_contractor', 'Sub Contractor')], max_length=50),
        ),
    ]
