# Generated by Django 5.0.6 on 2024-08-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksiterole',
            name='role',
            field=models.CharField(choices=[('epc_admin', 'EPC Admin'), ('epc', 'EPC User'), ('client', 'Client User'), ('sub_contractor', 'Sub Contractor'), ('quality_inspector', 'Quality Inspector')], max_length=50),
        ),
    ]
