# Generated by Django 5.0.6 on 2024-09-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_correctiveactionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('electrical', 'Electrical'), ('civil', 'Civil'), ('mechanical', 'Mechanical'), ('stores', 'Stores')], max_length=50, null=True),
        ),
    ]
