# Generated by Django 5.0.6 on 2024-09-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksiterole',
            name='role',
            field=models.CharField(choices=[('epc_admin', 'EPC Admin'), ('epc', 'EPC User'), ('client', 'Client User'), ('sub_contractor', 'Sub Contractor'), ('quality_inspector', 'Quality Inspector'), ('safety_officer', 'Safety Officer')], max_length=50),
        ),
    ]
