# Generated by Django 5.0.6 on 2024-09-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_worksiterole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.AlterField(
            model_name='correctiveactionuser',
            name='work_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_action_users', to='authentication.worksite'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(to='authentication.department'),
        ),
    ]
