# Generated by Django 5.0.6 on 2024-09-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_department_alter_correctiveactionuser_work_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='departments',
        ),
    ]
