# Generated by Django 5.0.6 on 2024-09-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_rename_department_user_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, to='authentication.department'),
        ),
    ]
