# Generated by Django 5.0.6 on 2024-09-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_user_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveactionuser',
            name='work_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_action_users', to='authentication.worksite'),
        ),
    ]
